### ISSUE TITLE
Create action to run github pages

### ISSUE THREAD

**Issue by gabrielbdornas** [gabrielbdornas/python-project-template#13]
It must run only on main branch docs files:

```
name: Publish Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**.md"
      - "mkdocs.yml"
  workflow_dispatch:

jobs:
  publish_documentation:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2

      - name: Check out repository
        uses: actions/checkout@v2
        with:  
          fetch-depth: 0

      - name: Create venv
        run: make venv

      - name: Install packages
        run: make install

      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Publish Documentation
        run: make gh-deploy
```

- [Reference Link](https://github.com/mkdocs/mkdocs/discussions/2369)
